phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase..
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase..
  build:
    commands:
      - echo Build started on 'date'
      - sudo apt-get update
      - sudo apt-get install awscli
  post_build:
    commands:
      - echo Build completed on 'date'
      
    - aws iam create-policy --policy-name cba-demo --policy-document file://s3creation.json
artifacts:
  files:
    - 'target/ccdemo.zip'
    

    