version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase..
      - aws --version
      
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase..
  build:
    commands:
      - echo Build started on 'date'
      - aws iam create-policy --policy-name cba-demo --policy-document file://s3creation.json
  post_build:
    commands:
      - echo Build completed on 'date' 
artifacts:
  files:
    - 'target/ccdemo.zip'
    

    